import Head from 'next/head'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />  
      </Head>

      <main className="max-w-5xl mx-auto px-2 pt-24">
       This is animation page
      </main>

    </>
  )
}